# find JPSemaphore

IF(NOT(JPReactor_LIBRARY AND JPReactor_INCLUDE_DIR))
	# search for include and library path
	FIND_PATH(JPReactor_INCLUDE_DIR  libJPReactor.h PATHS ${LOCAL_INC} )
	FIND_LIBRARY(JPReactor_LIBRARY JPReactor PATHS ${LOCAL_LIBS} )

	IF(JPReactor_INCLUDE_DIR AND JPReactor_LIBRARY)
		SET(JPReactor_FOUND TRUE)
		MESSAGE(STATUS "Found JPReactor: ${JPReactor_LIBRARY}")

	ELSE(JPReactor_INCLUDE_DIR AND JPReactor_LIBRARY)
		SET(JPReactor_FOUND FALSE)
		MESSAGE(SEND_ERROR "Could NOT find JPReactor")
	ENDIF(JPReactor_INCLUDE_DIR AND JPReactor_LIBRARY)
ENDIF( NOT ( JPReactor_LIBRARY AND JPReactor_INCLUDE_DIR) )
